[package]
name = "b64converter"
version = "1.1.0"
authors = ["Anders J. Andersen <andersj.andersen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.15"
base64 = "^0.13"
