[package]
name = "b64converter"
version = "1.2.0"
authors = ["Anders J. Andersen <andersj.andersen@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.1"
base64 = "0.21.0"

[profile.release]
strip = "debuginfo"